language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  # - "3.7-dev"  # 3.7 development branch (pandas not yet available)

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install coveralls
  - pip install codacy-coverage

# command to run tests
script: xvfb-run --server-args="-screen 0 1024x768x24" py.test --cov-report html:htmlcov --cov-report xml:coverage.xml --cov-report term --cov=cauldron ./cauldron/test

after_success:
    - codecov
    - coveralls
    - python-codacy-coverage -r coverage.xml
